### ISSUE TITLE
Export playGeigerTick function?

### ISSUE THREAD

**Issue by callumlocke** [kristiandupont/react-geiger#7]
This package is great, thanks for making it! I have a couple of cases where I want to use the same kind of geiger tick sound, but not for slow renders. There is a state combination in my app where I want to be aware of how often it occurs, and a tick sound during local dev would be perfect.

The code for playing audio in `Geiger.tsx` looks great. It would be cool if I could do `import { playGeigerTick } from 'react-geiger'` and then call it from an effect or wherever. Any chance you could export a public function along those lines?

**Comment by kristiandupont** [comment]
Done! :-)
