### ISSUE TITLE
[feature request] browser addon

### ISSUE THREAD

**Issue by david-morris** [kristiandupont/react-geiger#9]
In a perfect world, I'd be able to turn this on for a page, or even attach it to a component via the react dev tools.

Being able to "hook into" using Geiger without changing my package dependencies would be nice.

How much work are we talking? Does anyone already know any blockers?

**Comment by kristiandupont** [comment]
Heh, that would be cool but it certainly doesn't sound like a trivial task to me...

**Comment by david-morris** [comment]
Yeah, the easiest way to do this is probably to get really popular and then have the react devtools team interested in building the functionality in directly. "Not planned" would be totally understandable here, especially since this package installs smaller than several single files I have in my repo.

**Comment by kristiandupont** [comment]
Still, thanks for the idea!
